### ISSUE TITLE
Keyboard type options is hidden! Nothing inside!

### ISSUE THREAD

**Issue by iD7me** [tomaszpoliszuk/KeyboardController#1]

**Comment by tomaszpoliszuk** [comment]
There is bug in forked preferenceloader you are using.

You'll need preferenceloader from BigBoss repo - http://apt.thebigboss.org/repofiles/cydia/debs2.0/preferenceloader_2.2.5.deb or use alternative preferenceloader made by [ArtikusHG](https://github.com/ArtikusHG), [open sourced](https://github.com/ArtikusHG/PreferenceLoader), available on repo -> https://artikushg.github.io/
