### ISSUE TITLE
Edit keyboard type doesn’t show anything

### ISSUE THREAD

**Issue by gustisyailendra** [tomaszpoliszuk/KeyboardController#3]
https://i.imgur.com/RqBCvLu.png
![B794B6E8-F56A-40AF-AA91-66B701193648](https://user-images.githubusercontent.com/70874194/92347819-5c0c7800-f0fb-11ea-904e-4829ff45d789.png)

**Comment by tomaszpoliszuk** [comment]
There is bug in forked preferenceloader you are using.

You'll need preferenceloader from BigBoss repo - http://apt.thebigboss.org/repofiles/cydia/debs2.0/preferenceloader_2.2.5.deb or use alternative preferenceloader made by [ArtikusHG](https://github.com/ArtikusHG), [open sourced](https://github.com/ArtikusHG/PreferenceLoader), available on repo -> https://artikushg.github.io/
