### ISSUE TITLE
Scrolling through Emojis dismisses keyboard

### ISSUE THREAD

**Issue by d8xa** [tomaszpoliszuk/KeyboardController#4]
For some reason, scrolling horizontally on the Emoji keyboard is recognized as a swipe to dismiss. 
The problem occurs for all "swipe to dismiss" options except "disabled" (obviously).

Device: iPhone 6S+
iOS version: 14.0.1

**Comment by tomaszpoliszuk** [comment]
Hi - just released update that fixes this bug and adds new features (and support for iOS 12) - can you try version 1.1 and let me know if you have any issues?

**Comment by d8xa** [comment]
I'm so sorry, I completely forgot to check if my version was up to date. Yes, the update fixes it. Thank you!

**Comment by tomaszpoliszuk** [comment]
No need to apologise - update was published about the same time when you created this issue :)

So I'm closing this issue since [this bug is fixed](https://github.com/tomaszpoliszuk/KeyboardController/commit/4f3cb163a907910edddd6c7de26123c285e1f367), have a nice day!
